// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file TinyYOLO.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace YOLOv4ObjectDetection
{
    
    public sealed class TinyYOLOInput
    {
        public TensorFloat image; // shape(-1,3,416,416)
    }
    
    public sealed class TinyYOLOOutput
    {
        public TensorFloat grid; // shape(-1,125,13,13)
    }
    
    public sealed class TinyYOLOModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<TinyYOLOModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            TinyYOLOModel learningModel = new TinyYOLOModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<TinyYOLOOutput> EvaluateAsync(TinyYOLOInput input)
        {
            binding.Bind("image", input.image);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new TinyYOLOOutput();
            output.grid = result.Outputs["grid"] as TensorFloat;
            return output;
        }
    }
}

