// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file ImageClassifier.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace classifierPyTorch
{
    
    public sealed class ImageClassifierInput
    {
        public TensorFloat modelInput; // shape(-1,3,32,32)
    }
    
    public sealed class ImageClassifierOutput
    {
        public TensorFloat modelOutput; // shape(-1,10)
    }
    
    public sealed class ImageClassifierModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<ImageClassifierModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            ImageClassifierModel learningModel = new ImageClassifierModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<ImageClassifierOutput> EvaluateAsync(ImageClassifierInput input)
        {
            binding.Bind("modelInput", input.modelInput);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new ImageClassifierOutput();
            output.modelOutput = result.Outputs["modelOutput"] as TensorFloat;
            return output;
        }
    }
}

