// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file bestModel.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;


namespace classifierMLNETModel
{
    
    public sealed class bestModelInput
    {
        public ImageFeatureValue input1; // shape(-1,3,224,224)
    }
    
    public sealed class bestModelOutput
    {
        public TensorFloat output1; // shape(-1,3)
    }
    
    public sealed class bestModelModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<bestModelModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            bestModelModel learningModel = new bestModelModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<bestModelOutput> EvaluateAsync(bestModelInput input)
        {
            binding.Bind("input1", input.input1);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new bestModelOutput();
            output.output1 = result.Outputs["output1"] as TensorFloat;
            return output;
        }
    }
}

